name: BedWarsProxy
version: ${gitVer}${project.version}
description: Arena connector for BedWars2023 forked from andrei1058
main: com.andrei1058.bedwars.proxy.BedWarsProxy
author: Mr. Ceasar
api-version: '1.13'
softdepend:
  - Parties
  - Partys
  - PartyAndFriends
  - PlaceholderAPI
  - Spigot-Party-API-PAF
